(define (problem treasure_quest_problem)
  (:domain treasure_quest)
  (:objects
    entrance to_torcia2 lk43 te_tempo4 to_gas5 lv6 te_stagioni7 lk38 lv9 to_scudo10 lk111 te_statua12 te_oscurita13 lk214 to_asta_di_ferro15 treasure_antechamber16 treasure_room - room
    k1 k2 k3 k4 - key
    torcia panno_bagnato scudo asta_di_ferro - item
    p2 p4 p5 p7 p10 p12 p13 p15 p16 - puzzle
    n s e w - direction
  )
  (:init
    (at entrance)
    (life1) (life2) (life3)
    (has_item torcia)
    (has_item panno_bagnato)
    (has_item scudo)
    (has_item asta_di_ferro)
    (key_in_room k1 lk111)
    (key_in_room k2 lk214)
    (key_in_room k3 lk38)
    (key_in_room k4 lk43)
    (connected entrance to_torcia2 n)
    (connected entrance te_oscurita13 e)
    (connected entrance te_statua12 s)
    (connected to_torcia2 lk43 e)
    (connected to_torcia2 entrance s)
    (connected lk43 te_tempo4 e)
    (connected lk43 to_torcia2 w)
    (connected te_tempo4 lk214 s)
    (connected te_tempo4 lk43 w)
    (connected to_gas5 lv6 e)
    (connected lv6 te_stagioni7 s)
    (connected lv6 to_gas5 w)
    (connected te_stagioni7 lv6 n)
    (connected te_stagioni7 lk38 s)
    (connected lk38 te_stagioni7 n)
    (connected lk38 lv9 w)
    (connected lv9 lk38 e)
    (connected to_scudo10 lk214 n)
    (connected to_scudo10 lk111 w)
    (connected lk111 to_scudo10 e)
    (connected lk111 te_oscurita13 w)
    (connected te_statua12 entrance n)
    (connected te_statua12 lk214 e)
    (connected te_oscurita13 lk214 e)
    (connected te_oscurita13 lk111 s)
    (connected te_oscurita13 entrance w)
    (connected lk214 te_tempo4 n)
    (connected lk214 to_scudo10 e)
    (connected lk214 te_statua12 s)
    (connected lk214 te_oscurita13 w)
    (connected to_asta_di_ferro15 treasure_antechamber16 w)
    (connected treasure_antechamber16 to_asta_di_ferro15 e)
    (connected treasure_antechamber16 treasure_room w)
    (key_opens k1 te_tempo4)
    (key_opens k1 to_gas5)
    (key_opens k3 te_stagioni7)
    (key_opens k2 lv9)
    (key_opens k4 to_scudo10)
    (key_opens k1 to_asta_di_ferro15)
    (locked te_tempo4)
    (locked to_gas5)
    (locked te_stagioni7)
    (locked lv9)
    (locked to_scudo10)
    (locked to_asta_di_ferro15)
    (puzzle_in_room p2 to_torcia2) (trap_active to_torcia2) (answer_known p2)
    (puzzle_in_room p4 te_tempo4) (trap_active te_tempo4) (answer_known p4)
    (puzzle_in_room p5 to_gas5) (trap_active to_gas5) (answer_known p5)
    (puzzle_in_room p7 te_stagioni7) (trap_active te_stagioni7) (answer_known p7)
    (puzzle_in_room p10 to_scudo10) (trap_active to_scudo10) (answer_known p10)
    (puzzle_in_room p12 te_statua12) (trap_active te_statua12) (answer_known p12)
    (puzzle_in_room p13 te_oscurita13) (trap_active te_oscurita13) (answer_known p13)
    (puzzle_in_room p15 to_asta_di_ferro15) (trap_active to_asta_di_ferro15) (answer_known p15)
    (puzzle_in_room p16 treasure_antechamber16) (trap_active treasure_antechamber16) (answer_known p16)
    (trap_item_room to_torcia2 torcia)
    (trap_item_room to_gas5 panno_bagnato)
    (trap_item_room to_scudo10 scudo)
    (trap_item_room to_asta_di_ferro15 asta_di_ferro)

  )
  (:goal (and (at treasure_room) (not (dead))))
)