(define (problem treasure_quest_problem)
  (:domain treasure_quest)
  (:objects 
    n s e w - direction
    entrance bat_room treasure_room key_room_1 key_room_2 key_room_3 key_room_4 gas_room life_room_6 puzzle_room_5 puzzle_room_6 life_room_9 arrow_room puzzle_room_7 puzzle_room_8 flood_room treasure_antechamber - room
    k1 k2 k3 k4 - key
    torch water_cloth shield steel_pole - item
    p5 p6 p7 p8 p_ante - puzzle
  )
  (:init (at entrance) (life1) (life2) (life3)
    (has_item torch) (has_item water_cloth) (has_item shield) (has_item steel_pole)
    (key_in_room k1 key_room_1) (key_in_room k2 key_room_2) (key_in_room k3 key_room_3) (key_in_room k4 key_room_4)
    (key_opens k1 gas_room) (key_opens k3 flood_room) (key_opens k4 arrow_room)
    (locked gas_room) (locked flood_room) (locked arrow_room)
    (trap_item_room bat_room torch) (trap_active bat_room)
    (trap_item_room gas_room water_cloth) (trap_active gas_room)
    (trap_item_room arrow_room shield) (trap_active arrow_room)
    (trap_item_room flood_room steel_pole) (trap_active flood_room)
    (puzzle_in_room p5 puzzle_room_5) (trap_active puzzle_room_5) (answer_known p5)
    (puzzle_in_room p6 puzzle_room_6) (trap_active puzzle_room_6) (answer_known p6)
    (puzzle_in_room p7 puzzle_room_7) (trap_active puzzle_room_7) (answer_known p7)
    (puzzle_in_room p8 puzzle_room_8) (trap_active puzzle_room_8) (answer_known p8)
    (puzzle_in_room p_ante treasure_antechamber) (trap_active treasure_antechamber) (answer_known p_ante)
    (connected entrance bat_room n) (connected bat_room entrance s)
    (connected entrance puzzle_room_7 e) (connected puzzle_room_7 entrance w)
    (connected entrance puzzle_room_8 s) (connected puzzle_room_8 entrance n)
    (connected bat_room key_room_4 e) (connected key_room_4 bat_room w)
    (connected key_room_4 puzzle_room_5 e) (connected puzzle_room_5 key_room_4 w)
    (connected puzzle_room_5 gas_room e) (connected gas_room puzzle_room_5 w)
    (connected gas_room flood_room s) (connected flood_room gas_room n)
    (connected gas_room life_room_6 e) (connected life_room_6 gas_room w)
    (connected life_room_6 puzzle_room_6 s) (connected puzzle_room_6 life_room_6 n)
    (connected puzzle_room_6 key_room_3 s) (connected key_room_3 puzzle_room_6 n)
    (connected key_room_3 life_room_9 w) (connected life_room_9 key_room_3 e)
    (connected life_room_9 arrow_room w) (connected arrow_room life_room_9 e)
    (connected life_room_9 key_room_2 n) (connected key_room_2 life_room_9 s)
    (connected arrow_room key_room_1 w) (connected key_room_1 arrow_room e)
    (connected key_room_1 puzzle_room_7 s) (connected puzzle_room_7 key_room_1 n)
    (connected puzzle_room_7 key_room_2 e) (connected key_room_2 puzzle_room_7 w)
    (connected puzzle_room_8 key_room_1 e) (connected key_room_1 puzzle_room_8 w)
    (connected key_room_2 puzzle_room_8 s) (connected puzzle_room_8 key_room_2 n)
    (connected flood_room puzzle_room_6 e) (connected puzzle_room_6 flood_room w)
    (connected flood_room life_room_9 s) (connected life_room_9 flood_room n)
    (connected flood_room treasure_antechamber w) (connected treasure_antechamber flood_room e)
    (connected treasure_antechamber treasure_room n) (connected treasure_room treasure_antechamber s)

  )
  (:goal (and (at treasure_room) (not dead)))
)