(define (problem treasure_quest_problem)
  (:domain treasure_quest)
  (:objects
    room1 room2 room3 room4 room5 room6 room7 room8 room9 room10 room11 room12 room13 room14 room15 room16 room17 - room
    key1 key2 key3 key4 - key
    torch water_cloth shield steel_pole - item
    puzzle5 puzzle6 puzzle7 puzzle8 puzzle_antechamber - puzzle
    n s e w - string
  )
  (:init
    (at room1)
    (has_item torch)
    (has_item water_cloth)
    (has_item shield)
    (has_item steel_pole)
    (key_in_room key1 room11)
    (key_in_room key2 room14)
    (key_in_room key3 room8)
    (key_in_room key4 room3)
    (trap_item_room room2 torch)
    (trap_item_room room5 water_cloth)
    (trap_item_room room10 shield)
    (trap_item_room room15 steel_pole)
    (puzzle_in_room puzzle5 room4)
    (puzzle_in_room puzzle6 room7)
    (puzzle_in_room puzzle7 room12)
    (puzzle_in_room puzzle8 room13)
    (puzzle_in_room puzzle_antechamber room16)
    (trap_active room2)
    (trap_active room5)
    (trap_active room10)
    (trap_active room15)
    (trap_active room4)
    (trap_active room7)
    (trap_active room12)
    (trap_active room13)
    (trap_active room16)
    (key_opens key1 room4 room5)
    (key_opens key3 room7 room15)
    (key_opens key2 room9 room15)
    (key_opens key4 room9 room10)
    (connected room1 room2 n)
    (connected room1 room13 e)
    (connected room1 room12 s)
    (connected room2 room1 s)
    (connected room2 room3 e)
    (connected room3 room2 w)
    (connected room3 room4 e)
    (connected room4 room3 w)
    (connected room4 room14 s)
    (connected room4 room5 e)
    (connected room5 room4 w)
    (connected room5 room15 s)
    (connected room5 room6 e)
    (connected room6 room5 w)
    (connected room6 room7 s)
    (connected room7 room15 w)
    (connected room7 room8 s)
    (connected room8 room9 w)
    (connected room9 room10 w)
    (connected room9 room8 e)
    (connected room9 room15 n)
    (connected room10 room11 w)
    (connected room10 room9 e)
    (connected room10 room14 n)
    (connected room11 room13 w)
    (connected room11 room10 e)
    (connected room12 room14 e)
    (connected room12 room1 n)
    (connected room13 room1 w)
    (connected room13 room11 s)
    (connected room13 room14 e)
    (connected room14 room13 w)
    (connected room14 room12 s)
    (connected room14 room10 e)
    (connected room14 room4 n)
    (connected room15 room5 n)
    (connected room15 room7 e)
    (connected room15 room9 s)
    (connected room15 room16 w)
    (connected room16 room17 n)
    (door_locked room4 room5)
    (door_locked room7 room15)
    (door_locked room9 room15)
    (door_locked room9 room10)
    (safe_life_room room6)
    (safe_life_room room9)
    (lives_gt 3)
    (answer_known puzzle5)
    (answer_known puzzle6)
    (answer_known puzzle7)
    (answer_known puzzle8)

  )
  (:goal (and (at room17) (lives_gt 0)))
)